package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/peterbourgon/ff/v3/ffcli"
	"github.com/tamtom/play-console-cli/internal/cli/registry"
	"github.com/tamtom/play-console-cli/internal/cli/shared"
)

func main() {
	version := "dev"
	root := &ffcli.Command{
		Name:        "gplay",
		ShortUsage:  "gplay <command> [flags]",
		ShortHelp:   "A CLI for Google Play Console.",
		FlagSet:     flag.NewFlagSet("gplay", flag.ExitOnError),
		Subcommands: registry.Subcommands(version),
		UsageFunc:   shared.DefaultUsageFunc,
	}

	generateMarkdown(os.Stdout, root, "")
}

func generateMarkdown(w io.Writer, cmd *ffcli.Command, prefix string) {
	fullName := prefix
	if fullName == "" {
		fullName = cmd.Name
		fmt.Fprintf(w, "# %s CLI Reference\n\n", cmd.Name)
		fmt.Fprintf(w, "> Auto-generated by `go run tools/gendocs/main.go`. Do not edit manually.\n\n")
		fmt.Fprintf(w, "## Table of Contents\n\n")
		printTOC(w, cmd, "")
		fmt.Fprintf(w, "\n---\n\n")
	} else {
		fullName = prefix + " " + cmd.Name
	}

	if prefix != "" {
		fmt.Fprintf(w, "## %s\n\n", fullName)
		if cmd.ShortHelp != "" {
			fmt.Fprintf(w, "%s\n\n", cmd.ShortHelp)
		}
		if cmd.ShortUsage != "" {
			fmt.Fprintf(w, "```\n%s\n```\n\n", cmd.ShortUsage)
		}

		if cmd.FlagSet != nil {
			var flags []string
			cmd.FlagSet.VisitAll(func(f *flag.Flag) {
				flags = append(flags, fmt.Sprintf("| `--%s` | %s | `%s` |", f.Name, f.Usage, f.DefValue))
			})
			if len(flags) > 0 {
				fmt.Fprintln(w, "| Flag | Description | Default |")
				fmt.Fprintln(w, "|------|-------------|---------|")
				for _, f := range flags {
					fmt.Fprintln(w, f)
				}
				fmt.Fprintln(w)
			}
		}
		fmt.Fprintf(w, "---\n\n")
	}

	for _, sub := range cmd.Subcommands {
		generateMarkdown(w, sub, fullName)
	}
}

func printTOC(w io.Writer, cmd *ffcli.Command, prefix string) {
	for _, sub := range cmd.Subcommands {
		fullName := sub.Name
		if prefix != "" {
			fullName = prefix + " " + sub.Name
		}
		anchor := strings.ReplaceAll(fullName, " ", "-")
		fmt.Fprintf(w, "- [%s](#%s)\n", fullName, anchor)
		printTOC(w, sub, fullName)
	}
}
