// Package livesmoke contains the harness for live smoke tests that execute
// the compiled gplay binary against the Google Play API. Mutations are
// restricted to a single dedicated fixture app.
package livesmoke

import (
	"fmt"
	"strings"
)

// AllowedMutationPackage is the only package that live mutation tests may
// touch. It is a dedicated fixture app authorized for automated testing.
// This constant is intentionally not configurable via flags, workflow
// inputs, or environment variables.
const AllowedMutationPackage = "com.itdeveapps.stepsshare"

// NamePrefix marks every resource the live smoke suite creates. The janitor
// only deletes resources that carry this prefix.
const NamePrefix = "lsmoke"

// EnsureMutationAllowed returns an error unless pkg is exactly the fixture
// package. Callers must invoke it before every mutating CLI call.
func EnsureMutationAllowed(pkg string) error {
	if pkg != AllowedMutationPackage {
		return fmt.Errorf("mutation guard: package %q is not the fixture app %q; live mutations are refused", pkg, AllowedMutationPackage)
	}
	return nil
}

// ResourceName builds the canonical name for a created resource:
// lsmoke-<runID>-<kind>. The run ID makes leftovers attributable to a
// specific workflow run.
func ResourceName(runID, kind string) string {
	return fmt.Sprintf("%s-%s-%s", NamePrefix, runID, kind)
}

// IsManagedResourceName reports whether name was generated by ResourceName.
// The janitor uses it so it never deletes foreign resources.
func IsManagedResourceName(name string) bool {
	return strings.HasPrefix(name, NamePrefix+"-")
}

// ContractTestPrefix marks one-time products that the Go contract test
// creates (see internal/cli/monetizationpricing/integration_test.go).
const ContractTestPrefix = "ci_otp_"

// IsJanitorTarget reports whether the janitor may delete the resource with
// this name. Only names created by the live suite or the contract tests
// qualify. Every other name is a foreign resource and must survive.
func IsJanitorTarget(name string) bool {
	return IsManagedResourceName(name) || strings.HasPrefix(name, ContractTestPrefix)
}
