package docs

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/peterbourgon/ff/v3/ffcli"
	"github.com/tamtom/play-console-cli/internal/cli/shared"
)

// RootCommand is set by the caller to provide the root command tree.
var RootCommand *ffcli.Command

// GenerateCommand returns the docs generate subcommand.
func GenerateCommand() *ffcli.Command {
	fs := flag.NewFlagSet("docs generate", flag.ExitOnError)
	outputFile := fs.String("output-file", "GPLAY.md", "Output file path (use - for stdout)")

	return &ffcli.Command{
		Name:       "generate",
		ShortUsage: "gplay docs generate [--output-file <path>]",
		ShortHelp:  "Generate a markdown command reference from the CLI tree.",
		FlagSet:    fs,
		UsageFunc:  shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			if RootCommand == nil {
				return fmt.Errorf("docs generate: root command not set")
			}

			var w io.Writer
			if *outputFile == "-" {
				w = os.Stdout
			} else {
				f, err := os.Create(*outputFile)
				if err != nil {
					return fmt.Errorf("creating output file: %w", err)
				}
				defer f.Close()
				w = f
			}

			generateMarkdown(w, RootCommand, "")

			if *outputFile != "-" {
				fmt.Fprintf(os.Stderr, "Generated %s\n", *outputFile)
			}
			return nil
		},
	}
}

func generateMarkdown(w io.Writer, cmd *ffcli.Command, prefix string) {
	fullName := prefix
	if fullName == "" {
		fullName = cmd.Name
		fmt.Fprintf(w, "# %s CLI Reference\n\n", cmd.Name)
		fmt.Fprint(w, "> Auto-generated by `gplay docs generate`. Do not edit manually.\n\n")
		fmt.Fprint(w, "## Table of Contents\n\n")
		printTOC(w, cmd, "")
		fmt.Fprint(w, "\n---\n\n")
	} else {
		fullName = prefix + " " + cmd.Name
	}

	if prefix != "" {
		fmt.Fprintf(w, "## %s\n\n", fullName)
		if cmd.ShortHelp != "" {
			fmt.Fprintf(w, "%s\n\n", cmd.ShortHelp)
		}
		if cmd.ShortUsage != "" {
			fmt.Fprintf(w, "```\n%s\n```\n\n", cmd.ShortUsage)
		}

		// Print flags
		if cmd.FlagSet != nil {
			var flags []string
			cmd.FlagSet.VisitAll(func(f *flag.Flag) {
				flags = append(flags, fmt.Sprintf("| `--%s` | %s | `%s` |", f.Name, f.Usage, f.DefValue))
			})
			if len(flags) > 0 {
				fmt.Fprintln(w, "| Flag | Description | Default |")
				fmt.Fprintln(w, "|------|-------------|---------|")
				for _, f := range flags {
					fmt.Fprintln(w, f)
				}
				fmt.Fprintln(w)
			}
		}
		fmt.Fprint(w, "---\n\n")
	}

	// Recurse into subcommands
	for _, sub := range cmd.Subcommands {
		generateMarkdown(w, sub, fullName)
	}
}

func printTOC(w io.Writer, cmd *ffcli.Command, prefix string) {
	for _, sub := range cmd.Subcommands {
		fullName := sub.Name
		if prefix != "" {
			fullName = prefix + " " + sub.Name
		}
		anchor := strings.ReplaceAll(fullName, " ", "-")
		fmt.Fprintf(w, "- [%s](#%s)\n", fullName, anchor)
		printTOC(w, sub, fullName)
	}
	_ = sort.Strings // imported for potential future use
}
