package completion

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/peterbourgon/ff/v3/ffcli"

	"github.com/tamtom/play-console-cli/internal/cli/shared"
)

func CompletionCommand() *ffcli.Command {
	fs := flag.NewFlagSet("completion", flag.ExitOnError)
	return &ffcli.Command{
		Name:       "completion",
		ShortUsage: "gplay completion <shell>",
		ShortHelp:  "Generate shell completion scripts.",
		LongHelp: `Generate shell completion scripts for gplay.

To install completions:

Bash:
  gplay completion bash > /etc/bash_completion.d/gplay
  # or for user-local installation:
  gplay completion bash > ~/.bash_completion.d/gplay

Zsh:
  gplay completion zsh > "${fpath[1]}/_gplay"
  # or:
  gplay completion zsh > ~/.zfunc/_gplay
  # Make sure ~/.zfunc is in your fpath before compinit

Fish:
  gplay completion fish > ~/.config/fish/completions/gplay.fish

PowerShell:
  gplay completion powershell > gplay.ps1
  # Then source the script in your PowerShell profile`,
		FlagSet:   fs,
		UsageFunc: shared.DefaultUsageFunc,
		Subcommands: []*ffcli.Command{
			BashCommand(),
			ZshCommand(),
			FishCommand(),
			PowerShellCommand(),
		},
		Exec: func(ctx context.Context, args []string) error {
			if len(args) == 0 {
				return flag.ErrHelp
			}
			return flag.ErrHelp
		},
	}
}

func BashCommand() *ffcli.Command {
	fs := flag.NewFlagSet("completion bash", flag.ExitOnError)
	return &ffcli.Command{
		Name:       "bash",
		ShortUsage: "gplay completion bash",
		ShortHelp:  "Generate bash completion script.",
		FlagSet:    fs,
		UsageFunc:  shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			fmt.Fprint(os.Stdout, bashCompletion)
			return nil
		},
	}
}

func ZshCommand() *ffcli.Command {
	fs := flag.NewFlagSet("completion zsh", flag.ExitOnError)
	return &ffcli.Command{
		Name:       "zsh",
		ShortUsage: "gplay completion zsh",
		ShortHelp:  "Generate zsh completion script.",
		FlagSet:    fs,
		UsageFunc:  shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			fmt.Fprint(os.Stdout, zshCompletion)
			return nil
		},
	}
}

func FishCommand() *ffcli.Command {
	fs := flag.NewFlagSet("completion fish", flag.ExitOnError)
	return &ffcli.Command{
		Name:       "fish",
		ShortUsage: "gplay completion fish",
		ShortHelp:  "Generate fish completion script.",
		FlagSet:    fs,
		UsageFunc:  shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			fmt.Fprint(os.Stdout, fishCompletion)
			return nil
		},
	}
}

func PowerShellCommand() *ffcli.Command {
	fs := flag.NewFlagSet("completion powershell", flag.ExitOnError)
	return &ffcli.Command{
		Name:       "powershell",
		ShortUsage: "gplay completion powershell",
		ShortHelp:  "Generate PowerShell completion script.",
		FlagSet:    fs,
		UsageFunc:  shared.DefaultUsageFunc,
		Exec: func(ctx context.Context, args []string) error {
			fmt.Fprint(os.Stdout, powershellCompletion)
			return nil
		},
	}
}

const bashCompletion = `# gplay bash completion script
# Generated by gplay completion bash

_gplay_completions() {
    local cur prev words cword
    _init_completion || return

    local commands="auth edits bundles apks tracks listings images reviews details testers availability deobfuscation release promote rollout completion version"

    # Subcommands for each main command
    local auth_commands="init login logout status profiles use doctor"
    local edits_commands="create get validate commit delete"
    local bundles_commands="upload list"
    local apks_commands="upload list"
    local tracks_commands="list get update patch"
    local listings_commands="list get create update patch delete"
    local images_commands="list upload delete deleteall"
    local reviews_commands="list get reply"
    local details_commands="get update patch"
    local testers_commands="get update patch"
    local availability_commands="get"
    local deobfuscation_commands="upload"
    local rollout_commands="halt resume update complete"
    local completion_commands="bash zsh fish powershell"

    # Common flags
    local common_flags="--package --output --pretty"
    local edit_flags="--edit"
    local track_flags="--track"

    case "${cword}" in
        1)
            COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
            ;;
        2)
            case "${prev}" in
                auth)
                    COMPREPLY=($(compgen -W "${auth_commands}" -- "${cur}"))
                    ;;
                edits)
                    COMPREPLY=($(compgen -W "${edits_commands}" -- "${cur}"))
                    ;;
                bundles)
                    COMPREPLY=($(compgen -W "${bundles_commands}" -- "${cur}"))
                    ;;
                apks)
                    COMPREPLY=($(compgen -W "${apks_commands}" -- "${cur}"))
                    ;;
                tracks)
                    COMPREPLY=($(compgen -W "${tracks_commands}" -- "${cur}"))
                    ;;
                listings)
                    COMPREPLY=($(compgen -W "${listings_commands}" -- "${cur}"))
                    ;;
                images)
                    COMPREPLY=($(compgen -W "${images_commands}" -- "${cur}"))
                    ;;
                reviews)
                    COMPREPLY=($(compgen -W "${reviews_commands}" -- "${cur}"))
                    ;;
                details)
                    COMPREPLY=($(compgen -W "${details_commands}" -- "${cur}"))
                    ;;
                testers)
                    COMPREPLY=($(compgen -W "${testers_commands}" -- "${cur}"))
                    ;;
                availability)
                    COMPREPLY=($(compgen -W "${availability_commands}" -- "${cur}"))
                    ;;
                deobfuscation)
                    COMPREPLY=($(compgen -W "${deobfuscation_commands}" -- "${cur}"))
                    ;;
                rollout)
                    COMPREPLY=($(compgen -W "${rollout_commands}" -- "${cur}"))
                    ;;
                completion)
                    COMPREPLY=($(compgen -W "${completion_commands}" -- "${cur}"))
                    ;;
            esac
            ;;
        *)
            # Complete flags
            if [[ "${cur}" == -* ]]; then
                case "${words[1]}" in
                    release)
                        COMPREPLY=($(compgen -W "--package --track --bundle --apk --release-notes --rollout --status --version-name --wait --poll-interval --changes-not-sent-for-review --output --pretty" -- "${cur}"))
                        ;;
                    promote)
                        COMPREPLY=($(compgen -W "--package --from --to --rollout --status --release-notes --changes-not-sent-for-review --output --pretty" -- "${cur}"))
                        ;;
                    *)
                        COMPREPLY=($(compgen -W "${common_flags} ${edit_flags} ${track_flags}" -- "${cur}"))
                        ;;
                esac
            fi
            # Complete flag values
            case "${prev}" in
                --output)
                    COMPREPLY=($(compgen -W "json table markdown" -- "${cur}"))
                    ;;
                --track|--from|--to)
                    COMPREPLY=($(compgen -W "production beta alpha internal" -- "${cur}"))
                    ;;
                --status)
                    COMPREPLY=($(compgen -W "draft inProgress halted completed" -- "${cur}"))
                    ;;
                --file|--bundle|--apk)
                    _filedir
                    ;;
            esac
            ;;
    esac
}

complete -F _gplay_completions gplay
`

const zshCompletion = `#compdef gplay

# gplay zsh completion script
# Generated by gplay completion zsh

_gplay() {
    local -a commands
    commands=(
        'auth:Manage authentication profiles'
        'edits:Manage Google Play app edits'
        'bundles:Manage app bundles in an edit'
        'apks:Manage APKs in an edit'
        'tracks:Manage release tracks in an edit'
        'listings:Manage store listings'
        'images:Manage listing images'
        'reviews:Manage app reviews'
        'details:Manage app details'
        'testers:Manage testers for closed testing tracks'
        'availability:Check country availability for tracks'
        'deobfuscation:Manage deobfuscation files'
        'release:Create a complete release'
        'promote:Promote a release between tracks'
        'rollout:Manage staged rollouts'
        'completion:Generate shell completion scripts'
        'version:Print version information'
    )

    local -a auth_commands
    auth_commands=(
        'init:Initialize a new authentication profile'
        'login:Login with OAuth'
        'logout:Logout and remove credentials'
        'status:Show authentication status'
        'profiles:List all profiles'
        'use:Set the default profile'
        'doctor:Diagnose authentication issues'
    )

    local -a edits_commands
    edits_commands=(
        'create:Create a new edit'
        'get:Get an edit'
        'validate:Validate an edit'
        'commit:Commit an edit'
        'delete:Delete an edit'
    )

    local -a rollout_commands
    rollout_commands=(
        'halt:Halt a staged rollout'
        'resume:Resume a halted rollout'
        'update:Update rollout percentage'
        'complete:Complete a staged rollout'
    )

    local -a completion_commands
    completion_commands=(
        'bash:Generate bash completion script'
        'zsh:Generate zsh completion script'
        'fish:Generate fish completion script'
        'powershell:Generate PowerShell completion script'
    )

    _arguments -C \
        '1: :->command' \
        '2: :->subcommand' \
        '*: :->args'

    case $state in
        command)
            _describe -t commands 'gplay commands' commands
            ;;
        subcommand)
            case $words[2] in
                auth)
                    _describe -t auth_commands 'auth commands' auth_commands
                    ;;
                edits)
                    _describe -t edits_commands 'edits commands' edits_commands
                    ;;
                bundles)
                    _values 'bundles commands' 'upload' 'list'
                    ;;
                apks)
                    _values 'apks commands' 'upload' 'list'
                    ;;
                tracks)
                    _values 'tracks commands' 'list' 'get' 'update' 'patch'
                    ;;
                listings)
                    _values 'listings commands' 'list' 'get' 'create' 'update' 'patch' 'delete'
                    ;;
                images)
                    _values 'images commands' 'list' 'upload' 'delete' 'deleteall'
                    ;;
                reviews)
                    _values 'reviews commands' 'list' 'get' 'reply'
                    ;;
                details)
                    _values 'details commands' 'get' 'update' 'patch'
                    ;;
                testers)
                    _values 'testers commands' 'get' 'update' 'patch'
                    ;;
                availability)
                    _values 'availability commands' 'get'
                    ;;
                deobfuscation)
                    _values 'deobfuscation commands' 'upload'
                    ;;
                rollout)
                    _describe -t rollout_commands 'rollout commands' rollout_commands
                    ;;
                completion)
                    _describe -t completion_commands 'completion commands' completion_commands
                    ;;
            esac
            ;;
        args)
            case $words[2] in
                release)
                    _arguments \
                        '--package[Package name]:package:' \
                        '--track[Target track]:track:(production beta alpha internal)' \
                        '--bundle[Path to .aab file]:file:_files -g "*.aab"' \
                        '--apk[Path to .apk file]:file:_files -g "*.apk"' \
                        '--release-notes[Release notes JSON]:json:' \
                        '--rollout[Rollout fraction]:fraction:' \
                        '--status[Release status]:status:(draft inProgress halted completed)' \
                        '--version-name[Version name]:name:' \
                        '--wait[Wait for processing]' \
                        '--poll-interval[Poll interval]:duration:' \
                        '--output[Output format]:format:(json table markdown)' \
                        '--pretty[Pretty print JSON]'
                    ;;
                promote)
                    _arguments \
                        '--package[Package name]:package:' \
                        '--from[Source track]:track:(production beta alpha internal)' \
                        '--to[Destination track]:track:(production beta alpha internal)' \
                        '--rollout[Rollout fraction]:fraction:' \
                        '--status[Release status]:status:(draft inProgress halted completed)' \
                        '--output[Output format]:format:(json table markdown)' \
                        '--pretty[Pretty print JSON]'
                    ;;
                *)
                    _arguments \
                        '--package[Package name]:package:' \
                        '--edit[Edit ID]:edit:' \
                        '--track[Track name]:track:(production beta alpha internal)' \
                        '--output[Output format]:format:(json table markdown)' \
                        '--pretty[Pretty print JSON]'
                    ;;
            esac
            ;;
    esac
}

_gplay "$@"
`

const fishCompletion = `# gplay fish completion script
# Generated by gplay completion fish

# Disable file completion by default
complete -c gplay -f

# Main commands
complete -c gplay -n '__fish_use_subcommand' -a auth -d 'Manage authentication profiles'
complete -c gplay -n '__fish_use_subcommand' -a edits -d 'Manage Google Play app edits'
complete -c gplay -n '__fish_use_subcommand' -a bundles -d 'Manage app bundles in an edit'
complete -c gplay -n '__fish_use_subcommand' -a apks -d 'Manage APKs in an edit'
complete -c gplay -n '__fish_use_subcommand' -a tracks -d 'Manage release tracks in an edit'
complete -c gplay -n '__fish_use_subcommand' -a listings -d 'Manage store listings'
complete -c gplay -n '__fish_use_subcommand' -a images -d 'Manage listing images'
complete -c gplay -n '__fish_use_subcommand' -a reviews -d 'Manage app reviews'
complete -c gplay -n '__fish_use_subcommand' -a details -d 'Manage app details'
complete -c gplay -n '__fish_use_subcommand' -a testers -d 'Manage testers for closed testing tracks'
complete -c gplay -n '__fish_use_subcommand' -a availability -d 'Check country availability for tracks'
complete -c gplay -n '__fish_use_subcommand' -a deobfuscation -d 'Manage deobfuscation files'
complete -c gplay -n '__fish_use_subcommand' -a release -d 'Create a complete release'
complete -c gplay -n '__fish_use_subcommand' -a promote -d 'Promote a release between tracks'
complete -c gplay -n '__fish_use_subcommand' -a rollout -d 'Manage staged rollouts'
complete -c gplay -n '__fish_use_subcommand' -a completion -d 'Generate shell completion scripts'
complete -c gplay -n '__fish_use_subcommand' -a version -d 'Print version information'

# Auth subcommands
complete -c gplay -n '__fish_seen_subcommand_from auth' -a init -d 'Initialize a new authentication profile'
complete -c gplay -n '__fish_seen_subcommand_from auth' -a login -d 'Login with OAuth'
complete -c gplay -n '__fish_seen_subcommand_from auth' -a logout -d 'Logout and remove credentials'
complete -c gplay -n '__fish_seen_subcommand_from auth' -a status -d 'Show authentication status'
complete -c gplay -n '__fish_seen_subcommand_from auth' -a profiles -d 'List all profiles'
complete -c gplay -n '__fish_seen_subcommand_from auth' -a use -d 'Set the default profile'
complete -c gplay -n '__fish_seen_subcommand_from auth' -a doctor -d 'Diagnose authentication issues'

# Edits subcommands
complete -c gplay -n '__fish_seen_subcommand_from edits' -a create -d 'Create a new edit'
complete -c gplay -n '__fish_seen_subcommand_from edits' -a get -d 'Get an edit'
complete -c gplay -n '__fish_seen_subcommand_from edits' -a validate -d 'Validate an edit'
complete -c gplay -n '__fish_seen_subcommand_from edits' -a commit -d 'Commit an edit'
complete -c gplay -n '__fish_seen_subcommand_from edits' -a delete -d 'Delete an edit'

# Rollout subcommands
complete -c gplay -n '__fish_seen_subcommand_from rollout' -a halt -d 'Halt a staged rollout'
complete -c gplay -n '__fish_seen_subcommand_from rollout' -a resume -d 'Resume a halted rollout'
complete -c gplay -n '__fish_seen_subcommand_from rollout' -a update -d 'Update rollout percentage'
complete -c gplay -n '__fish_seen_subcommand_from rollout' -a complete -d 'Complete a staged rollout'

# Completion subcommands
complete -c gplay -n '__fish_seen_subcommand_from completion' -a bash -d 'Generate bash completion script'
complete -c gplay -n '__fish_seen_subcommand_from completion' -a zsh -d 'Generate zsh completion script'
complete -c gplay -n '__fish_seen_subcommand_from completion' -a fish -d 'Generate fish completion script'
complete -c gplay -n '__fish_seen_subcommand_from completion' -a powershell -d 'Generate PowerShell completion script'

# Common flags
complete -c gplay -l package -d 'Package name (applicationId)'
complete -c gplay -l edit -d 'Edit ID'
complete -c gplay -l track -d 'Track name' -a 'production beta alpha internal'
complete -c gplay -l output -d 'Output format' -a 'json table markdown'
complete -c gplay -l pretty -d 'Pretty print JSON output'

# Release flags
complete -c gplay -n '__fish_seen_subcommand_from release' -l bundle -d 'Path to .aab file' -r -F
complete -c gplay -n '__fish_seen_subcommand_from release' -l apk -d 'Path to .apk file' -r -F
complete -c gplay -n '__fish_seen_subcommand_from release' -l release-notes -d 'Release notes JSON'
complete -c gplay -n '__fish_seen_subcommand_from release' -l rollout -d 'Rollout fraction (0.0-1.0)'
complete -c gplay -n '__fish_seen_subcommand_from release' -l status -d 'Release status' -a 'draft inProgress halted completed'
complete -c gplay -n '__fish_seen_subcommand_from release' -l version-name -d 'Version name'
complete -c gplay -n '__fish_seen_subcommand_from release' -l wait -d 'Wait for processing'
complete -c gplay -n '__fish_seen_subcommand_from release' -l poll-interval -d 'Poll interval'

# Promote flags
complete -c gplay -n '__fish_seen_subcommand_from promote' -l from -d 'Source track' -a 'production beta alpha internal'
complete -c gplay -n '__fish_seen_subcommand_from promote' -l to -d 'Destination track' -a 'production beta alpha internal'
`

const powershellCompletion = `# gplay PowerShell completion script
# Generated by gplay completion powershell

Register-ArgumentCompleter -Native -CommandName gplay -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @{
        'gplay' = @('auth', 'edits', 'bundles', 'apks', 'tracks', 'listings', 'images', 'reviews', 'details', 'testers', 'availability', 'deobfuscation', 'release', 'promote', 'rollout', 'completion', 'version')
        'auth' = @('init', 'login', 'logout', 'status', 'profiles', 'use', 'doctor')
        'edits' = @('create', 'get', 'validate', 'commit', 'delete')
        'bundles' = @('upload', 'list')
        'apks' = @('upload', 'list')
        'tracks' = @('list', 'get', 'update', 'patch')
        'listings' = @('list', 'get', 'create', 'update', 'patch', 'delete')
        'images' = @('list', 'upload', 'delete', 'deleteall')
        'reviews' = @('list', 'get', 'reply')
        'details' = @('get', 'update', 'patch')
        'testers' = @('get', 'update', 'patch')
        'availability' = @('get')
        'deobfuscation' = @('upload')
        'rollout' = @('halt', 'resume', 'update', 'complete')
        'completion' = @('bash', 'zsh', 'fish', 'powershell')
    }

    $flagCompletions = @{
        '--output' = @('json', 'table', 'markdown')
        '--track' = @('production', 'beta', 'alpha', 'internal')
        '--from' = @('production', 'beta', 'alpha', 'internal')
        '--to' = @('production', 'beta', 'alpha', 'internal')
        '--status' = @('draft', 'inProgress', 'halted', 'completed')
    }

    $elements = $commandAst.CommandElements
    $command = 'gplay'

    for ($i = 1; $i -lt $elements.Count; $i++) {
        $element = $elements[$i].ToString()
        if (-not $element.StartsWith('-') -and $commands.ContainsKey($element)) {
            $command = $element
        }
    }

    # Check if we're completing a flag value
    $prevElement = $elements[-1].ToString()
    if ($flagCompletions.ContainsKey($prevElement)) {
        $flagCompletions[$prevElement] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
        return
    }

    # Complete commands or subcommands
    if ($wordToComplete -like '-*') {
        # Flag completion
        @('--package', '--edit', '--track', '--output', '--pretty') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)
        }
    } else {
        # Command completion
        $commands[$command] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'Command', $_)
        }
    }
}
`
